In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [2]:
file_path = "Sales Data-Jan'21 to Dec'21.xlsx"

df = pd.read_excel(file_path)

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 78429
Columns: 38

In [4]:
df.head()

,Customer Name,Customer Code,Ship To Cust Code,Ship To Cust Name,Bill Type,C,Inv.No,ODN,BUS. PLACE,SO.No,Date,Week,Incoterms,PO.No,PI.No,Cust.Nature,Territory Code,Territory,Inv.Date,Brand,Sub-Brand,Prime Brand,Folder/Non-Folder,Material,Material Desc.,Division,Division Text,Thickness,Vol.CBM,Design(LAM),Finish(LAM),Billed Qty,Sales unit,Billed Qty(SQM),Billed Qty(PCS),Billed Qty(NA),Billed Qty (CBM),Billed Qty (MT)
0,N.K. Traders,10016196,10016196,N.K. Traders,ZFAC,NaN,2027009169,F22027008891,PH01,1129145721,2021-01-01,1,Free on road,NaN,NaN,CD-customer,511995,Prelam -Jaipur,2021-01-01,NaN,NaN,NaN,NaN,HMCI055PC18300305O,5.5 MM CEN PLN MDF- DI-E2 C-1.83 X0.305,22,MDF - Plain,5.50,2.533,NaN,NaN,825,PC,460.515,825,0,2.533,2.003
1,N.K. Traders,10016196,10016196,N.K. Traders,ZFAC,NaN,2027009169,F22027008891,PH01,1129145721,2021-01-01,1,Free on road,NaN,NaN,CD-customer,511995,Prelam -Jaipur,2021-01-01,NaN,NaN,NaN,NaN,HMCI070PC18300305O,7 MM CEN PLN MDF- DI-E2 C-1.83 X0.305,22,MDF - Plain,7.00,4.419,NaN,NaN,1131,PC,631.324,1131,0,4.419,3.491
2,N.K. Traders,10016196,10016196,N.K. Traders,ZFAC,NaN,2027009169,F22027008891,PH01,1129145721,2021-01-01,1,Free on road,NaN,NaN,CD-customer,511995,Prelam -Jaipur,2021-01-01,NaN,NaN,NaN,NaN,HMCI110PC19830610O,11 MM CEN PLN MDF-DI-E2 C-1.983X0.61,22,MDF - Plain,11.00,8.116,NaN,NaN,610,PC,737.856,610,0,8.116,0.000
3,N.K. Traders,10016196,10016196,N.K. Traders,ZFAC,NaN,2027009169,F22027008891,PH01,1129145721,2021-01-01,1,Free on road,NaN,NaN,CD-customer,511995,Prelam -Jaipur,2021-01-01,NaN,NaN,NaN,NaN,HMCI168PC18300610O,16.75 MM CEN PLN MDF- DI-E2 C-1.83 X0.61,22,MDF - Plain,16.75,6.675,NaN,NaN,357,PC,398.519,357,0,6.675,5.272
4,N.K. Traders,10016196,10016196,N.K. Traders,ZFAC,NaN,2027009169,F22027008891,PH01,1129145721,2021-01-01,1,Free on road,NaN,NaN,CD-customer,511995,Prelam -Jaipur,2021-01-01,NaN,NaN,NaN,NaN,HMCI168PC18300305O,16.75 MM CEN PLN MDF-DI-E2 C-1.83 X0.305,22,MDF - Plain,16.75,0.654,NaN,NaN,70,PC,39.074,70,0,0.654,0.517

In [5]:
for col in df.columns:
    print(col)

Customer Name
Customer Code
Ship To Cust Code
Ship To Cust Name
Bill Type
C
Inv.No
ODN
BUS. PLACE
SO.No
Date
Week
Incoterms
PO.No
PI.No
Cust.Nature
Territory Code
Territory
Inv.Date
Brand
Sub-Brand
Prime Brand
Folder/Non-Folder
Material
Material Desc.
Division
Division Text
Thickness
Vol.CBM
Design(LAM)
Finish(LAM)
Billed Qty
Sales unit
Billed Qty(SQM)
Billed Qty(PCS)
Billed Qty(NA)
Billed Qty (CBM)
Billed Qty (MT)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78429 entries, 0 to 78428
Data columns (total 38 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer Name      78429 non-null  object
 1   Customer Code      78429 non-null  int64
 2   Ship To Cust Code  78429 non-null  int64
 3   Ship To Cust Name  78429 non-null  object
 4   Bill Type          78429 non-null  object
 5   C                  1414 non-null   object
 6   Inv.No             78429 non-null  int64
 7   ODN                78429 non-null  object
 8   BUS. PLACE         78429 non-null  object
 9   SO.No              78429 non-null  int64
 10  Date               78429 non-null  datetime64[ns]
 11  Week               78429 non-null  int64
 12  Incoterms          78429 non-null  object
 13  PO.No              0 non-null      float64
 14  PI.No              0 non-null      float64
 15  Cust.Nature        78429 non-null  object
 16  Territory Code     78429 non-null  int64
 17  Territory          78429 non-null  object
 18  Inv.Date           78429 non-null  datetime64[ns]
 19  Brand              0 non-null      float64
 20  Sub-Brand          0 non-null      float64
 21  Prime Brand        0 non-null      float64
 22  Folder/Non-Folder  0 non-null      float64
 23  Material           78429 non-null  object
 24  Material Desc.     78429 non-null  object
 25  Division           78429 non-null  int64
 26  Division Text      78429 non-null  object
 27  Thickness          78429 non-null  float64
 28  Vol.CBM            78429 non-null  float64
 29  Design(LAM)        0 non-null      float64
 30  Finish(LAM)        0 non-null      float64
 31  Billed Qty         78429 non-null  int64
 32  Sales unit         78429 non-null  object
 33  Billed Qty(SQM)    78429 non-null  float64
 34  Billed Qty(PCS)    78429 non-null  int64
 35  Billed Qty(NA)     78429 non-null  int64
 36  Billed Qty (CBM)   78429 non-null  float64
 37  Billed Qty (MT)    78429 non-null  float64
dtypes: datetime64[ns](2), float64(13), int64(10), object(13)
memory usage: 22.7+ MB

In [7]:
missing_values = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Percentage': round((df.isnull().sum()/len(df))*100,2)
})

missing_values.sort_values(
    by='Missing Values',
    ascending=False
)

                   Missing Values  Percentage
Brand                       78429       100.0
Finish(LAM)                 78429       100.0
Folder/Non-Folder           78429       100.0
PI.No                       78429       100.0
PO.No                       78429       100.0
Prime Brand                 78429       100.0
Design(LAM)                 78429       100.0
Sub-Brand                   78429       100.0
C                           77015        98.2
Sales unit                      0         0.0
Billed Qty                      0         0.0
Billed Qty(SQM)                 0         0.0
Vol.CBM                         0         0.0
Thickness                       0         0.0
Billed Qty(PCS)                 0         0.0
Billed Qty(NA)                  0         0.0
Division Text                   0         0.0
Division                        0         0.0
Material Desc.                  0         0.0
Material                        0         0.0
Billed Qty (CBM)                0         0.0
Customer Name                   0         0.0
Customer Code                   0         0.0
Inv.Date                        0         0.0
Territory                       0         0.0
Territory Code                  0         0.0
Cust.Nature                     0         0.0
Incoterms                       0         0.0
Week                            0         0.0
Date                            0         0.0
SO.No                           0         0.0
BUS. PLACE                      0         0.0
ODN                             0         0.0
Inv.No                          0         0.0
Bill Type                       0         0.0
Ship To Cust Name               0         0.0
Ship To Cust Code               0         0.0
Billed Qty (MT)                 0         0.0

In [8]:
duplicates = df.duplicated().sum()

print("Duplicate Records:", duplicates)

Duplicate Records: 79

In [9]:
unique_values = pd.DataFrame({
    'Column': df.columns,
    'Unique Values': [df[col].nunique() for col in df.columns]
})

unique_values.sort_values(
    by='Unique Values',
    ascending=False
)

               Column  Unique Values
6              Inv.No          14929
7                 ODN          14840
9               SO.No          13957
24     Material Desc.           5055
23           Material           5055
28            Vol.CBM           4176
36   Billed Qty (CBM)           4172
37    Billed Qty (MT)           2727
33    Billed Qty(SQM)           2027
34    Billed Qty(PCS)           1210
31         Billed Qty           1210
2   Ship To Cust Code           1097
3   Ship To Cust Name           1082
1       Customer Code            632
0       Customer Name            626
18           Inv.Date            359
10               Date            342
17          Territory             69
16     Territory Code             69
27          Thickness             30
4           Bill Type              9
12          Incoterms              8
11               Week              5
15        Cust.Nature              4
25           Division              2
26      Division Text              2
32         Sales unit              1
8          BUS. PLACE              1
5                   C              1
35     Billed Qty(NA)              1
13              PO.No              0
22  Folder/Non-Folder              0
21        Prime Brand              0
29        Design(LAM)              0
30        Finish(LAM)              0
20          Sub-Brand              0
14              PI.No              0
19              Brand              0

In [10]:
df.describe()

,Customer Code,Ship To Cust Code,Inv.No,SO.No,Date,Week,PO.No,PI.No,Territory Code,Inv.Date,Brand,Sub-Brand,Prime Brand,Folder/Non-Folder,Division,Thickness,Vol.CBM,Design(LAM),Finish(LAM),Billed Qty,Billed Qty(SQM),Billed Qty(PCS),Billed Qty(NA),Billed Qty (CBM),Billed Qty (MT)
count,7.842900e+04,7.842900e+04,7.842900e+04,7.842900e+04,78429,78429.000000,0.0,0.0,78429.00000,78429,0.0,0.0,0.0,0.0,78429.000000,78429.000000,78429.000000,0.0,0.0,78429.000000,78429.000000,78429.000000,78429.0,78429.000000,78429.000000
mean,1.002643e+07,1.002698e+07,2.076203e+09,1.173897e+09,2021-07-01 16:29:09.393719040,2.826710,NaN,NaN,499712.58815,2021-07-11 05:20:14.688444416,NaN,NaN,NaN,NaN,24.676357,10.550829,2.234069,NaN,NaN,115.752745,340.375425,115.752745,0.0,2.234118,0.705471
min,1.000006e+07,1.000006e+07,9.004280e+07,1.129142e+09,2020-10-21 00:00:00,1.000000,NaN,NaN,111111.00000,2021-01-01 00:00:00,NaN,NaN,NaN,NaN,22.000000,1.900000,-30.743000,NaN,NaN,-2250.000000,-6697.800000,-2250.000000,0.0,-30.743000,-29.694000
25%,1.001362e+07,1.001372e+07,2.027200e+09,1.129149e+09,2021-03-11 00:00:00,2.000000,NaN,NaN,510995.00000,2021-03-26 00:00:00,NaN,NaN,NaN,NaN,22.000000,5.500000,0.513000,NaN,NaN,20.000000,59.536000,20.000000,0.0,0.514000,0.000000
50%,1.001452e+07,1.001547e+07,2.127004e+09,1.129153e+09,2021-07-21 00:00:00,3.000000,NaN,NaN,511595.00000,2021-07-23 00:00:00,NaN,NaN,NaN,NaN,22.000000,9.750000,1.340000,NaN,NaN,50.000000,148.840000,50.000000,0.0,1.340000,0.000000
75%,1.001716e+07,1.001802e+07,2.127008e+09,1.129157e+09,2021-10-07 00:00:00,4.000000,NaN,NaN,511996.00000,2021-10-17 00:00:00,NaN,NaN,NaN,NaN,30.000000,16.750000,2.783000,NaN,NaN,108.000000,327.448000,108.000000,0.0,2.783000,0.500000
max,2.000044e+07,2.000044e+07,2.177300e+09,2.829110e+09,2021-12-31 00:00:00,5.000000,NaN,NaN,516595.00000,2021-12-31 00:00:00,NaN,NaN,NaN,NaN,30.000000,35.000000,35.567000,NaN,NaN,5788.000000,12922.289000,5788.000000,0.0,35.567000,44.880000
std,2.825992e+05,2.825744e+05,2.311277e+08,1.555576e+08,NaN,1.255771,NaN,NaN,35599.22060,NaN,NaN,NaN,NaN,NaN,3.774672,6.241803,3.561083,NaN,NaN,238.426807,689.564079,238.426807,0.0,3.561118,2.194699

In [11]:
df.describe(include='all')

,Customer Name,Customer Code,Ship To Cust Code,Ship To Cust Name,Bill Type,C,Inv.No,ODN,BUS. PLACE,SO.No,Date,Week,Incoterms,PO.No,PI.No,Cust.Nature,Territory Code,Territory,Inv.Date,Brand,Sub-Brand,Prime Brand,Folder/Non-Folder,Material,Material Desc.,Division,Division Text,Thickness,Vol.CBM,Design(LAM),Finish(LAM),Billed Qty,Sales unit,Billed Qty(SQM),Billed Qty(PCS),Billed Qty(NA),Billed Qty (CBM),Billed Qty (MT)
count,78429,7.842900e+04,7.842900e+04,78429,78429,1414,7.842900e+04,78429,78429,7.842900e+04,78429,78429.000000,78429,0.0,0.0,78429,78429.00000,78429,78429,0.0,0.0,0.0,0.0,78429,78429,78429.000000,78429,78429.000000,78429.000000,0.0,0.0,78429.000000,78429,78429.000000,78429.000000,78429.0,78429.000000,78429.000000
unique,626,NaN,NaN,1082,9,1,NaN,14840,1,NaN,NaN,NaN,8,NaN,NaN,4,NaN,69,NaN,NaN,NaN,NaN,NaN,5055,5055,NaN,2,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
top,Sachdeva Enterprises,NaN,NaN,Balaji Sales Corporation,ZFAC,X,NaN,F22027008928,PH01,NaN,NaN,NaN,Free on road,NaN,NaN,CD-customer,NaN,Prelam -Ghaziabad,NaN,NaN,NaN,NaN,NaN,HMCI019PA24401220O,1.9 MM CEN PLN MDF-DI-E2- A-2.44X1.22,NaN,MDF - Plain,NaN,NaN,NaN,NaN,NaN,PC,NaN,NaN,NaN,NaN,NaN
freq,3075,NaN,NaN,2263,70615,1414,NaN,196,78429,NaN,NaN,NaN,68824,NaN,NaN,71454,NaN,13294,NaN,NaN,NaN,NaN,NaN,3275,3275,NaN,52191,NaN,NaN,NaN,NaN,NaN,78429,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.002643e+07,1.002698e+07,NaN,NaN,NaN,2.076203e+09,NaN,NaN,1.173897e+09,2021-07-01 16:29:09.393719040,2.826710,NaN,NaN,NaN,NaN,499712.58815,NaN,2021-07-11 05:20:14.688444416,NaN,NaN,NaN,NaN,NaN,NaN,24.676357,NaN,10.550829,2.234069,NaN,NaN,115.752745,NaN,340.375425,115.752745,0.0,2.234118,0.705471
min,NaN,1.000006e+07,1.000006e+07,NaN,NaN,NaN,9.004280e+07,NaN,NaN,1.129142e+09,2020-10-21 00:00:00,1.000000,NaN,NaN,NaN,NaN,111111.00000,NaN,2021-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,22.000000,NaN,1.900000,-30.743000,NaN,NaN,-2250.000000,NaN,-6697.800000,-2250.000000,0.0,-30.743000,-29.694000
25%,NaN,1.001362e+07,1.001372e+07,NaN,NaN,NaN,2.027200e+09,NaN,NaN,1.129149e+09,2021-03-11 00:00:00,2.000000,NaN,NaN,NaN,NaN,510995.00000,NaN,2021-03-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,22.000000,NaN,5.500000,0.513000,NaN,NaN,20.000000,NaN,59.536000,20.000000,0.0,0.514000,0.000000
50%,NaN,1.001452e+07,1.001547e+07,NaN,NaN,NaN,2.127004e+09,NaN,NaN,1.129153e+09,2021-07-21 00:00:00,3.000000,NaN,NaN,NaN,NaN,511595.00000,NaN,2021-07-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,22.000000,NaN,9.750000,1.340000,NaN,NaN,50.000000,NaN,148.840000,50.000000,0.0,1.340000,0.000000
75%,NaN,1.001716e+07,1.001802e+07,NaN,NaN,NaN,2.127008e+09,NaN,NaN,1.129157e+09,2021-10-07 00:00:00,4.000000,NaN,NaN,NaN,NaN,511996.00000,NaN,2021-10-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,NaN,16.750000,2.783000,NaN,NaN,108.000000,NaN,327.448000,108.000000,0.0,2.783000,0.500000
max,NaN,2.000044e+07,2.000044e+07,NaN,NaN,NaN,2.177300e+09,NaN,NaN,2.829110e+09,2021-12-31 00:00:00,5.000000,NaN,NaN,NaN,NaN,516595.00000,NaN,2021-12-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,NaN,35.000000,35.567000,NaN,NaN,5788.000000,NaN,12922.289000,5788.000000,0.0,35.567000,44.880000
std,NaN,2.825992e+05,2.825744e+05,NaN,NaN,NaN,2.311277e+08,NaN,NaN,1.555576e+08,NaN,1.255771,NaN,NaN,NaN,NaN,35599.22060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.774672,NaN,6.241803,3.561083,NaN,NaN,238.426807,NaN,689.564079,238.426807,0.0,3.561118,2.194699

In [12]:
datatype_summary = pd.DataFrame({
    'Column': df.columns,
    'Data Type': df.dtypes
})

datatype_summary

                              Column       Data Type
Customer Name          Customer Name          object
Customer Code          Customer Code           int64
Ship To Cust Code  Ship To Cust Code           int64
Ship To Cust Name  Ship To Cust Name          object
Bill Type                  Bill Type          object
C                                  C          object
Inv.No                        Inv.No           int64
ODN                              ODN          object
BUS. PLACE                BUS. PLACE          object
SO.No                          SO.No           int64
Date                            Date  datetime64[ns]
Week                            Week           int64
Incoterms                  Incoterms          object
PO.No                          PO.No         float64
PI.No                          PI.No         float64
Cust.Nature              Cust.Nature          object
Territory Code        Territory Code           int64
Territory                  Territory          object
Inv.Date                    Inv.Date  datetime64[ns]
Brand                          Brand         float64
Sub-Brand                  Sub-Brand         float64
Prime Brand              Prime Brand         float64
Folder/Non-Folder  Folder/Non-Folder         float64
Material                    Material          object
Material Desc.        Material Desc.          object
Division                    Division           int64
Division Text          Division Text          object
Thickness                  Thickness         float64
Vol.CBM                      Vol.CBM         float64
Design(LAM)              Design(LAM)         float64
Finish(LAM)              Finish(LAM)         float64
Billed Qty                Billed Qty           int64
Sales unit                Sales unit          object
Billed Qty(SQM)      Billed Qty(SQM)         float64
Billed Qty(PCS)      Billed Qty(PCS)           int64
Billed Qty(NA)        Billed Qty(NA)           int64
Billed Qty (CBM)    Billed Qty (CBM)         float64
Billed Qty (MT)      Billed Qty (MT)         float64

In [13]:
date_columns = df.select_dtypes(
    include=['datetime64[ns]']
).columns

print(date_columns)

Index(['Date', 'Inv.Date'], dtype='object')

In [14]:
important_columns = [
    'Territory',
    'Customer Name',
    'Material',
    'Division Text',
    'Thickness'
]

for col in important_columns:
    
    if col in df.columns:
        print("\n")
        print("="*50)
        print(col)
        print("="*50)
        
        print("Unique Values:", df[col].nunique())
        
        print(df[col].value_counts().head(10))

==================================================
Territory
==================================================
Unique Values: 69
Territory
Prelam -Ghaziabad    13294
Prelam -Delhi         9717
Prelam-Ludhiana       9413
Prelam -Jaipur        4796
Prelam -Lucknow       4738
Prejap1               3717
Prelam -Gurgaon       3543
Prelam -Ahmedabad     2806
Prelam -Indore        2622
Prelam -Chennai       2235
Name: count, dtype: int64


==================================================
Customer Name
==================================================
Unique Values: 626
Customer Name
Sachdeva Enterprises                   3075
Balaji Sales Corporation               2266
Jaipur Bikaner Trading Company Agen    2149
Gauri Nandan Wood Products             1436
Sri Senthur tradings                   1413
Mega Marketers                         1369
HIND PLYWOOD                           1337
Sehgal Plywood & Timber Merchants      1245
Tanishka enterprises                   1177
Banke bihari plywood agency            1114
Name: count, dtype: int64


==================================================
Material
==================================================
Unique Values: 5055
Material
HMCI019PA24401220O    3275
HMCI033PA24401220O    2712
HMCI110PA24401220O    2623
HMCI055PA24401220O    2503
HMCW055AA24401220O    2294
HMCW168AA24401220O    2220
HMCI046PA24401220O    1930
HMCW120AA24401220O    1892
HMCI165PA24401220O    1786
HMCW180AA24401220O    1621
Name: count, dtype: int64


==================================================
Division Text
==================================================
Unique Values: 2
Division Text
MDF - Plain        52191
MDF - Laminated    26238
Name: count, dtype: int64


==================================================
Thickness
==================================================
Unique Values: 30
Thickness
5.50     11387
16.75     8307
18.00     7155
16.50     5516
11.00     5486
7.50      4730
3.30      4464
17.00     4045
1.90      3633
12.00     3206
Name: count, dtype: int64

In [15]:
volume_columns = [
    'Billed Qty',
    'Billed Qty(SQM)',
    'Billed Qty(PCS)',
    'Billed Qty(CBM)',
    'Billed Qty(MT)'
]

for col in volume_columns:
    
    if col in df.columns:
        
        print("\n")
        print(col)
        
        print("Total:", df[col].sum())
        print("Mean :", df[col].mean())
        print("Max  :", df[col].max())

Billed Qty
Total: 9078372
Mean : 115.75274452052174
Max  : 5788


Billed Qty(SQM)
Total: 26695304.224
Mean : 340.3754252126127
Max  : 12922.289


Billed Qty(PCS)
Total: 9078372
Mean : 115.75274452052174
Max  : 5788

In [16]:
volume_columns = [
    'Billed Qty',
    'Billed Qty(SQM)',
    'Billed Qty(PCS)',
    'Billed Qty(CBM)',
    'Billed Qty(MT)'
]

for col in volume_columns:
    
    if col in df.columns:
        
        print("\n")
        print(col)
        
        print("Total:", df[col].sum())
        print("Mean :", df[col].mean())
        print("Max  :", df[col].max())

Billed Qty
Total: 9078372
Mean : 115.75274452052174
Max  : 5788


Billed Qty(SQM)
Total: 26695304.224
Mean : 340.3754252126127
Max  : 12922.289


Billed Qty(PCS)
Total: 9078372
Mean : 115.75274452052174
Max  : 5788

In [17]:
drop_cols = [
    'PO.No',
    'PI.No',
    'Brand',
    'Sub-Brand',
    'Prime Brand',
    'Folder/Non-Folder',
    'Design(LAM)',
    'Finish(LAM)',
    'c'
]

In [18]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 78429
Columns: 38

In [19]:
duplicates = df.duplicated().sum()

print("Duplicate Records:", duplicates)

Duplicate Records: 79

In [20]:
df = df.drop_duplicates()

print("New Shape:", df.shape)

New Shape: (78350, 38)

In [21]:
df['Inv.Date'] = pd.to_datetime(df['Inv.Date'])
df['Date'] = pd.to_datetime(df['Date'])

print(df['Inv.Date'].min())
print(df['Inv.Date'].max())

2021-01-01 00:00:00
2021-12-31 00:00:00

In [22]:
df['Year'] = df['Inv.Date'].dt.year

df['Month'] = df['Inv.Date'].dt.month

df['Month_Name'] = df['Inv.Date'].dt.month_name()

df['Quarter'] = df['Inv.Date'].dt.quarter

df['Day'] = df['Inv.Date'].dt.day

df['Day_Name'] = df['Inv.Date'].dt.day_name()

In [23]:
df['Year_Month'] = df['Inv.Date'].dt.to_period('M').astype(str)

df[['Inv.Date', 'Year_Month']].head()

    Inv.Date Year_Month
0 2021-01-01    2021-01
1 2021-01-01    2021-01
2 2021-01-01    2021-01
3 2021-01-01    2021-01
4 2021-01-01    2021-01

In [24]:
df[['Year',
    'Month',
    'Month_Name',
    'Quarter',
    'Day',
    'Day_Name',
    'Year_Month']].head()

   Year  Month Month_Name  Quarter  Day Day_Name Year_Month
0  2021      1    January        1    1   Friday    2021-01
1  2021      1    January        1    1   Friday    2021-01
2  2021      1    January        1    1   Friday    2021-01
3  2021      1    January        1    1   Friday    2021-01
4  2021      1    January        1    1   Friday    2021-01

In [25]:
print("Total CBM Volume:")
print(df['Billed Qty (CBM)'].sum())

print("\nAverage Volume:")
print(df['Billed Qty (CBM)'].mean())

Total CBM Volume:
175154.15500000003

Average Volume:
2.2355348436502873

In [26]:
business_summary = {
    "Total Records": len(df),
    "Customers": df['Customer Name'].nunique(),
    "Territories": df['Territory'].nunique(),
    "Materials": df['Material'].nunique(),
    "Divisions": df['Division Text'].nunique(),
    "Thickness Levels": df['Thickness'].nunique()
}

business_summary

{'Total Records': 78350,
 'Customers': 626,
 'Territories': 69,
 'Materials': 5055,
 'Divisions': 2,
 'Thickness Levels': 30}

In [27]:
df.to_csv(
    "sales_cleaned.csv",
    index=False
)

print("Cleaned Dataset Saved Successfully")

Cleaned Dataset Saved Successfully